# This configuration will build a Docker container containing
# an Envoy proxy that routes to Google.

FROM envoyproxy/envoy:v1.9.0
# FROM envoyproxy/envoy:latest
RUN apt-get update
# COPY bootstrap-ads.yaml /etc/bootstrap-ads.yaml
CMD /usr/local/bin/envoy -c /etc/bootstrap-ads.yaml